name = "VolumeEstimation"
uuid = "5dc268c4-7dbc-45e8-9d5a-a4858d7b40d1"
version = "0.1.0"
authors = ["Praharsh Suryadevara"]

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
PyMBAR = "ea233917-d838-44e9-aef6-29db41966de8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extensions]
VolumeEstimationPlotsExt = ["Plots", "Statistics"]

[compat]
CommonSolve = "0.2"
Pigeons = "0.4"
Plots = "1"
PyMBAR = "0.1"
Statistics = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
