name = "Volumes"
uuid = "5dc268c4-7dbc-45e8-9d5a-a4858d7b40d1"
version = "0.1.0"
authors = ["Praharsh Suryadevara"]

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
ForwardDiff = "0.10.39"
MCMCChains = "7.7.0"
Plots = "1.41.6"
StatsPlots = "0.15.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
